# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure('2') do |config|
  config.vm.box      = 'ubuntu/trusty64'
  config.vm.hostname = 'dcase-mldac'

  config.vm.network :forwarded_port, guest: 8888, host: 8888

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end
  
  config.vm.synced_folder "notebooks/", "/home/vagrant/notebooks"
  config.vm.synced_folder "code/", "/home/vagrant/code"
  config.vm.synced_folder "Task4", "/home/vagrant/Task4"

  # Provisioning
  config.vm.provision :shell, path: 'bootstrap.sh', keep_color: true

end
